# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b8c06b7c9dba783279093deea9eae3c5082ef78349ce665e39c5d6d9c2188d0fef2b9e87df0149bbde0ca0fe2f8661222d1733540388b364924871b65628fe7

test:
  secret_key_base: 3225456a97ed28fb7a07cdf7f5ca67a350c7b387c46a1498d7f2aac3ed570d93c31263f28163bc11c58967778e2a688e4a1affe4eec85185bf6bf97125ffb0a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
